config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :communities do
   resources :posts
 end

  root to: "public#index"

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :communities
  has_many :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
belongs_to :account
has_many :posts
validates_presence_of :url, :name, :rules

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  belongs_to :community

  validates_presence_of :title, :body, :account_id, :community_id


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
before_action :authenticate_account!, except: [ :index, :show ]
before_action :set_community, only: [:show]



def index
  @communities = Community.all
end

def show
  @community = Community.find(params[:id])
end

def new
  @community = Community.new
end

def create

    @community = Community.new (community_params)
    @community.account_id = current_account.id

     if @community.save
       redirect_to communities_path
     else
       render :new
      end
  end
#   @community = Community.new(community_params)
#
#   respond_to do |format|
#     if @community.save
#       format.html { redirect_to @community, notice: 'Communite was successfully created.' }
#       format.json { render action: 'show', status: :created, location: @community }
#     else
#       format.html { render action: 'new' }
#       format.json { render json: @community.errors, status: :unprocessable_entity }
#     end
#   end
# end



private

def set_community
  @community = Community.find(params[:id])
end

def community_params
   params.require(:community).permit(:name, :url, :rules)
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_account!, except: [ :index, :show ]
before_action :set_post, only: [:show]



def index
  @posts = Post.all
end

def show
  @post = Post.find(params[:id])
end

def new
  @community = Community.find(params[:community_id])
  @post = Post.new
end

def create

    @post = Post.new (post_params)
    @post.account_id = current_account.id
    @post.community_id = params[:community_id]

     if @post.save
       redirect_to community_path(@post.community_id)
     else
       @community = Community.find(params[:community_id])
       render :new
      end
  end
#   @community = Community.new(community_params)
#
#   respond_to do |format|
#     if @community.save
#       format.html { redirect_to @community, notice: 'Communite was successfully created.' }
#       format.json { render action: 'show', status: :created, location: @community }
#     else
#       format.html { render action: 'new' }
#       format.json { render json: @community.errors, status: :unprocessable_entity }
#     end
#   end
# end

private

def set_post
  @post = Post.find(params[:id])
end

def post_params
   params.require(:post).permit(:title, :body)
end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def index
    @communities = Community.all.limit(5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/communities/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for Community.new do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :rules %>
      <%= f.text_area :rules, class: "form-control" %>
    </div>

<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/communities/index.html.erb
<% if account_signed_in? %>
  <div class="float-right">
  <%= link_to "Create New Community", new_community_path, class: "btn btn-outline-primary" %>
  </div>
<% end %>

<% if @communities.size > 0 %>
<% @communities.each do |community| %>
<div class="card">
   <h3><%= link_to community.name %></h3>
   <h5><%= community.rules %></h5>
</div>
<% end %>
<% else %>

<p> No comunities to display</p>
<% end %>

app/views/communities/new.html.erb
<h2> New Community </h2>

<%= render partial: "form" %>

app/views/communities/show.html.erb
<%= link_to "Create new post", new_community_post_path(@community), class: "btn btn-primary float-right" %>

<%= @community.name %>

<p><%= simple_format @community.rules %></p>

app/views/layouts/_footer.html.erb
footer

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pt-3 pb-3 border_bottom">
      <div class="float-right">
        <% if account_signed_in? %>
        <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "btn btn-primary"%>
        <% else %>
        <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary"%>
        <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-primary"%>
          <% end %>
      </div>
      <p class="h3"><%= link_to "Reddit Clone", root_path %> </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
              <%= yield %>
        </div>
      </div>
    </div>


    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for [@community, @post] do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control" %>
    </div>

<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/posts/edit.html.erb
<h2> Edit Post </h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2> New Post </h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<%= simple_format @post.body %>